### ISSUE TITLE
Clairctl cannot pull from docker registry

### ISSUE THREAD

**Issue by jdel** [jgsqware/clairctl#3]
I am facing an issue trying to pull from the Docker hub with clairctl:

```
sf-clair ~ # clairctl --log-level debug pull jgsqware/registry-ui:latest
DEBU[0000] Using config file: /root/clairctl.yml
client quit unexpectedly
FATA[0004] retrieving manifest for "jgsqware/registry-ui:latest": Received error when trying to fetch the specified tag: it might not exist or you do not have access
```

This used to work with hyperclair. 

I am using the following config:

```
sf-clair ~ # clairctl health

Clair: ✔
sf-clair ~ # clairctl version

Clairctl version
sf-clair ~ # cat clairctl.yml
clair:
  port: 6060
  healthPort: 6061
  uri: http://clair
  priority: Low
  report:
    path: /var/opt/data/hyperclair/reports
    format: html
clairctl:
  tempFolder: /var/opt/tmp/hyperclair
```
