### ISSUE TITLE
clairctl doesn't handle ~ in yml config file

### ISSUE THREAD

**Issue by jdel** [jgsqware/clairctl#37]
I am not sure this is done on purpose or not, but I just spend a couple of minites trying to find out where my reports were generated.

Turns out clairctl created a ~ directory in my home directory, which is not what most people will expect.

For reference, my clairctl.yml file looks like this:

```
clair:                                                             
  port: 6060                                                       
  healthPort: 6061                                             
  uri: http://localhost                                            
  priority: Low                                                    
  report:                                                          
    path: ~/dev/jdel/playground/clair-2.0-rc1/data/clairctl-reports
    format: html                                                   
clairctl:                                                          
  port: 57330                                                      
  tempfolder: ~/dev/jdel/playground/clair-2.0-rc1/data/clairctl-tmp
```

Removing the ~/ put the reports (and tmp directory too) exactly where i wanted it.
