### ISSUE TITLE
Clairctl cannot pull from custom secure registry

### ISSUE THREAD

**Issue by jdel** [jgsqware/clairctl#5]
Clairctl cannot pull from my custom secure registry running https.

```
sf-clair ~ # clairctl --log-level debug pull registry.mydomain.net/core/custom-nginx
DEBU[0000] Using config file: /root/clairctl.yml
client quit unexpectedly
FATA[0000] retrieving manifest for "registry.mydomain.net/core/custom-nginx": Get http://registry.mydomain.net/v2/: dial tcp 172.16.1.8:80: getsockopt: connection refused
```

`docker pull` can pull from `registry.mydomain.net`.

This used to work with the binary I compiled from this hyperclair fork: https://github.com/murat1985/hyperclair

I am using the following config:

```
sf-clair ~ # clairctl health

Clair: ✔
sf-clair ~ # clairctl version

Clairctl version
sf-clair ~ # cat clairctl.yml
clair:
  port: 6060
  healthPort: 6061
  uri: http://clair
  priority: Low
  report:
    path: /var/opt/data/hyperclair/reports
    format: html
clairctl:
  tempFolder: /var/opt/tmp/hyperclair
```
